#!/usr/bin/env node
import { readFile, writeFile } from 'node:fs/promises'
import { basename } from 'node:path'

const args = process.argv.slice(2)
const getArg = (name) => {
  const index = args.indexOf(name)
  return index >= 0 ? args[index + 1] : undefined
}

const APP_URL = (process.env.APP_URL || process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000').replace(/\/$/, '')
const email = getArg('--email') || process.env.SMOKE_EMAIL || `smoke+${Date.now()}@revisamicv.lat`
const cvPath = getArg('--cv') || process.env.SMOKE_CV_PATH
const jobPath = getArg('--job') || process.env.SMOKE_JOB_PATH
const skipPaidApis = args.includes('--skip-paid-apis')
const outputPdf = getArg('--out') || '/tmp/revisamicv-smoke.pdf'

const checks = []

function ok(name, details = '') {
  checks.push({ name, status: 'ok', details })
  console.log(`✅ ${name}${details ? ` — ${details}` : ''}`)
}

function fail(name, error) {
  checks.push({ name, status: 'fail', details: String(error?.message || error) })
  console.error(`❌ ${name} — ${String(error?.message || error)}`)
}

async function assertFetch(name, path, options = {}, expectedStatuses = [200]) {
  const res = await fetch(`${APP_URL}${path}`, options)
  if (!expectedStatuses.includes(res.status)) {
    const body = await res.text().catch(() => '')
    throw new Error(`HTTP ${res.status}: ${body.slice(0, 300)}`)
  }
  ok(name, `HTTP ${res.status}`)
  return res
}

async function run() {
  console.log(`Smoke testing RevisaMiCV at ${APP_URL}`)
  console.log(`Email: ${email}`)

  try {
    await assertFetch('Landing page loads', '/')
  } catch (err) { fail('Landing page loads', err) }

  try {
    await assertFetch('Signup page loads', '/signup')
  } catch (err) { fail('Signup page loads', err) }

  try {
    await assertFetch('Dashboard page loads', '/dashboard')
  } catch (err) { fail('Dashboard page loads', err) }

  try {
    const pdfRes = await assertFetch(
      'PDF generation endpoint works',
      '/api/generate-pdf',
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          outputLanguage: 'spanish',
          optimizedCV: {
            headline: 'Smoke Test Candidate',
            summary: 'Generated by automated smoke test.',
            coreCompetencies: ['ATS', 'Product', 'Automation'],
            experience: [{ title: 'Founder', company: 'RevisaMiCV', dates: '2026', bullets: ['Validated PDF export.'] }],
          },
        }),
      }
    )
    const buffer = Buffer.from(await pdfRes.arrayBuffer())
    if (!buffer.subarray(0, 4).equals(Buffer.from('%PDF'))) throw new Error('Response is not a PDF')
    await writeFile(outputPdf, buffer)
    ok('Downloaded generated PDF', outputPdf)
  } catch (err) { fail('PDF generation endpoint works', err) }

  if (!skipPaidApis) {
    try {
      const userRes = await assertFetch(
        'User/token endpoint responds',
        '/api/user',
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ email }),
        },
        [200, 503]
      )
      const data = await userRes.json().catch(() => ({}))
      if (userRes.status === 503) ok('User/token endpoint blocked by config', data.message || 'needs Supabase config')
    } catch (err) { fail('User/token endpoint responds', err) }

    try {
      const histRes = await assertFetch(
        'History endpoint responds',
        '/api/history',
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ email }),
        },
        [200, 503]
      )
      const data = await histRes.json().catch(() => ({}))
      if (histRes.status === 503) ok('History endpoint blocked by config', data.message || 'needs Supabase config')
    } catch (err) { fail('History endpoint responds', err) }
  }

  if (cvPath && jobPath && !skipPaidApis) {
    try {
      const cvBuffer = await readFile(cvPath)
      const jobDescription = await readFile(jobPath, 'utf8')
      const form = new FormData()
      form.append('email', email)
      form.append('outputLanguage', 'spanish')
      form.append('jobDescription', jobDescription)
      form.append('cv', new Blob([cvBuffer]), basename(cvPath))

      const res = await assertFetch('Full CV processing endpoint responds', '/api/process-cv', { method: 'POST', body: form }, [200, 402, 503])
      const data = await res.json().catch(() => ({}))
      if (res.status !== 200) ok('Full CV processing returned expected gated state', data.message || data.error || `HTTP ${res.status}`)
    } catch (err) { fail('Full CV processing endpoint responds', err) }
  } else {
    console.log('ℹ️ Skipping full /api/process-cv test. Pass --cv path --job path after production config is ready.')
  }

  const failed = checks.filter((check) => check.status === 'fail')
  console.log(`\nSmoke test summary: ${checks.length - failed.length}/${checks.length} checks passed`)
  if (failed.length) process.exit(1)
}

run().catch((err) => {
  console.error(err)
  process.exit(1)
})
